language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - tip

before_script:
  - psql -c 'CREATE USER ottaconf;' -U postgres
  - psql -c 'CREATE DATABASE ottaconf OWNER ottaconf;' -U postgres
  - psql -f db/schema-v1.sql -U ottaconf
